name: Generate Datas

on:
  schedule: # execute a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Atualizar dados e publicar
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Gerar gráfico de contribuições da cobra (Snake Animation)
      - name: Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: lbrjanssen
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Passo 2: Publicar no GitHub Pages
      - name: Publicar no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
